# Generated by Django 4.2.7 on 2024-08-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcardid',
            old_name='user_id',
            new_name='bk_user_id',
        ),
        migrations.RenameField(
            model_name='browsinghistory',
            old_name='user_id',
            new_name='bh_user_id',
        ),
        migrations.RenameField(
            model_name='receivingaddress',
            old_name='user_id',
            new_name='rad_user_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='r_comment_id',
        ),
        migrations.RenameField(
            model_name='shopproductclassify',
            old_name='shop_id',
            new_name='spc_shop_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shop_id',
            new_name='user_shop_id',
        ),
        migrations.RenameField(
            model_name='usertocomment',
            old_name='comment_id',
            new_name='ucm_comment_id',
        ),
        migrations.RenameField(
            model_name='usertocomment',
            old_name='user_id',
            new_name='ucm_user_id',
        ),
        migrations.RenameField(
            model_name='usertocoupon',
            old_name='coupon_id',
            new_name='uc_coupon_id',
        ),
        migrations.RenameField(
            model_name='usertocoupon',
            old_name='user_id',
            new_name='uc_user_id',
        ),
        migrations.RenameField(
            model_name='usertoproductcollect',
            old_name='product_collect_id',
            new_name='upc_product_collect_id',
        ),
        migrations.RenameField(
            model_name='usertoproductcollect',
            old_name='user_id',
            new_name='upc_user_id',
        ),
        migrations.RenameField(
            model_name='usertoproductorder',
            old_name='product_order_id',
            new_name='upo_product_order_id',
        ),
        migrations.RenameField(
            model_name='usertoproductorder',
            old_name='user_id',
            new_name='upo_user_id',
        ),
        migrations.RenameField(
            model_name='usertoshopcollect',
            old_name='shop_id',
            new_name='usc_shop_id',
        ),
        migrations.RenameField(
            model_name='usertoshopcollect',
            old_name='user_id',
            new_name='usc_user_id',
        ),
        migrations.RenameField(
            model_name='usertoshoppingtrolley',
            old_name='shopping_trolley_id',
            new_name='ust_shopping_trolley_id',
        ),
        migrations.RenameField(
            model_name='usertoshoppingtrolley',
            old_name='user_id',
            new_name='ust_user_id',
        ),
    ]
