# Generated by Django 4.2.7 on 2024-08-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_user_id_bankcardid_bk_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_shop_id',
            new_name='shop',
        ),
    ]
