# Generated by Django 4.2.7 on 2024-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_user_shop_id_user_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcardid',
            old_name='bk_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='browsinghistory',
            old_name='bh_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='receivingaddress',
            old_name='rad_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='r_comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='shopproductclassify',
            old_name='spc_shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='usertocomment',
            old_name='ucm_comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='usertocomment',
            old_name='ucm_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertocoupon',
            old_name='uc_coupon_id',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='usertocoupon',
            old_name='uc_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoproductcollect',
            old_name='upc_product_collect_id',
            new_name='product_collect',
        ),
        migrations.RenameField(
            model_name='usertoproductcollect',
            old_name='upc_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoproductorder',
            old_name='upo_product_order_id',
            new_name='product_order',
        ),
        migrations.RenameField(
            model_name='usertoproductorder',
            old_name='upo_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoshopcollect',
            old_name='usc_shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='usertoshopcollect',
            old_name='usc_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoshoppingtrolley',
            old_name='ust_shopping_trolley_id',
            new_name='shopping_trolley',
        ),
        migrations.RenameField(
            model_name='usertoshoppingtrolley',
            old_name='ust_user_id',
            new_name='user',
        ),
    ]
