# Generated by Django 4.2.7 on 2024-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_bk_user_id_bankcardid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautypersonalcare',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='beautypersonalcare',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='books',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='books',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='car',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='car',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='computer',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='computer',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='giftflowers',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='giftflowers',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='home',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='home',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='householdappliances',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='householdappliances',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='maternalandchild',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='maternalandchild',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='menshoes',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='menshoes',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='menswear',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='menswear',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
        migrations.AddField(
            model_name='womenshoes',
            name='product_classify_id',
            field=models.CharField(help_text='产品分类ID', max_length=255, null=True, verbose_name='产品分类ID'),
        ),
        migrations.AddField(
            model_name='womenshoes',
            name='product_classify_name',
            field=models.CharField(help_text='产品分类名称', max_length=64, null=True, verbose_name='产品分类名称'),
        ),
    ]
