# Generated by Django 4.2.7 on 2024-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_shopproductclassify_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_discount',
            field=models.FloatField(blank=True, default=0.0, help_text='优惠券折扣', verbose_name='优惠券折扣'),
        ),
        migrations.AlterField(
            model_name='productcollect',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shoppingtrolley',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shopproductclassify',
            name='price',
            field=models.FloatField(blank=True, default=0.0, help_text='价格', verbose_name='价格'),
        ),
    ]
