# Generated by Django 4.2.7 on 2024-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_browsinghistory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_id',
            field=models.CharField(blank=True, help_text='产品ID', max_length=255, null=True, verbose_name='产品ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shop_id',
            field=models.CharField(blank=True, help_text='店铺ID', max_length=255, null=True, verbose_name='店铺ID'),
        ),
    ]
